openapi: "3.0.1"
info:
  version:  1.0.0 | 26.09.2026
  title: MS TicketCheck
  description: API проверки электронного билета на входе
security:
  - BearerAuth: []
  - OAuth2: []
servers:
  - url: /api/v1
  - url: https://{Host}/{EnvironmentPrefix}{MicroserviceName}/api/v1
    variables:
        Host:
          default: proverochka.ru
          description: Host на котором развернут микросервис
        EnvironmentPrefix:
          default: ''
          description: |
            Префикс конкретного тестового стенда, выделенного под задачу (feature environment).
            Фактически позволяет окончательно идентифицировать host микросервиса, т.к. хостинге мс в кластере они все хостятся на одном dns - условном host.ru
        MicroserviceName:
          default: ticket-check
          description: |
            Имя под которым микросервис развернут в кластере микросервисов
            Фактически позволяет окончательно идентифицировать host микросервиса при обращениях к нему
tags:
    - name: ticket-check operations
      description: Тэгирование методов для логической группировки по предметной области, например методы работающие с проверкой билетов стоит тэгировать как ticket-check operations
paths:
  /tickets:
    get:
      tags: 
        - ticket-check operations
      operationId: GetTicket
      summary: Получить список билетов
      description: Метод возвращает список билетов. При запросе можно отфильтровать список
      parameters:
        - in: query
          name: ticketFilter
          required: true
          schema:
            $ref: "#/components/parameters/ticketFilter"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketsRp"
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Service Error


    post:
      tags: 
        - ticket-check operations
      operationId: CreateTicketCheck
      summary: Проверить билет
      description: Метод создает результат проверки билета с его уникальным идентификатором
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketsRp'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                  $ref: '#/components/parameters/ticketId'
        204:
          description: No Content
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Service Error
  /tickets/{ticketId}:  
    delete:
      tags: 
        - ticket-check operations
      operationId: deleteTicket
      summary: Удалить билет по его идентификатору
      description: Метод удаляет объект по его идентификатору
      parameters:
        - in: path
          name: ticketId
          required: true
          schema:
            $ref: "#/components/parameters/ticketId"
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Service Error
    put:
      tags: 
        - ticket-check operations
      operationId: UpdateTicket
      summary: Обновить билет
      description: Метод обновляет объект по его идентификатору по атрибутам переданным в запросе
      parameters:
        - in: path
          name: ticketId
          required: true
          schema:
            $ref: "#/components/parameters/ticketId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketRq'
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Service Error
components:
  securitySchemes:
      BearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
      OAuth2:
         type: oauth2
         flows:
          password:
            tokenUrl: https://auth.tusvc.bcs.ru/auth/realms/perseus/protocol/openid-connect/token
            scopes: {}
  parameters:  
    ticketId:
      name: ticketId
      in: path
      description: Уникальный идентификатор
      required: true
      schema:
        type: string
        format: uuid
    ticketFilter:
      name: ticketFilter
      in: query
      description: Фильтр параметр
      required: true
      schema:
        $ref: '#/components/schemas/ticketFilter'
  schemas:
    ticketFilter:
      description: Фильтр параметр билета
      type: string
    TicketsRp: 
        description: Список объектов билет
        type: array
        items:
          $ref: '#/components/schemas/Ticket'
    Ticket:
      type: object
      description: Объект билет
      required: 
        - ticketId
      properties:
        result:
         type: string
         description: Результат проверки
        status:
         type: string
         description: Статус билета
        eventMatch:
         type: boolean
         description: Признак принадлежности билета мероприятию
    TicketRq:
      $ref: '#/components/schemas/Ticket'