openapi: "3.0.1"
info:
  version: 1.0.0
  title: Parking History Service API
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: parking-history

paths:
  /parking-sessions: 
    get:
      tags: [parking-history]
      summary: Получить историю парковок водителя
      parameters:
        - in: query
          name: driverId
          required: true
          schema: { type: string }
        - in: query
          name: dateFrom
          schema: { type: string, format: date }
        - in: query
          name: dateTo
          schema: { type: string, format: date }
        - in: query
          name: paymentStatus
          schema: { type: string, enum: [Оплачено, Не оплачено, В процессе] }
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sessionId: { type: string }
                    location: { type: string }
                    startTime: { type: string, format: date-time }
                    endTime: { type: string, format: date-time }
                    cost: { type: number }
                    paymentStatus: { type: string }

  /parking-sessions/{sessionId}: 
    get:
      tags: [parking-history]
      summary: Получить детальную информацию по сессии
      parameters:
        - in: path
          name: sessionId
          required: true 
          schema: { type: string }
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId: { type: string }
                  location: { type: string }
                  startTime: { type: string, format: date-time }
                  endTime: { type: string, format: date-time }
                  duration: { type: string }
                  cost: { type: number }
                  paymentStatus: { type: string }