openapi: 3.0.3
info:
  title: orders-service
  description: API микросервиса заявок QuickFix. Отвечает за создание заявки на ремонт, приём заявки мастером и отметку о завершении работы.
  version: "1.0.0 | 26.09.2026"
servers:
  - url: /api/v1

paths:
  /orders:
    post:
      tags:
        - Orders
      summary: Создать заявку
      description: Заказчик создаёт заявку на ремонт с описанием проблемы и адресом
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [customerId, category, description, address]
              properties:
                customerId:
                  type: integer
                  format: int64
                category:
                  type: string
                description:
                  type: string
                address:
                  type: string
      responses:
        '201': 
          description: Заявка создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: integer
                  status:
                    type: string
                  customerId:
                    type: integer
                  masterId:
                    type: integer
                  category:
                    type: string
                  description:
                    type: string
                  address:
                    type: string
        '400':
          description: Некорректные входные данные
        '401':
          description: Отсутствует или недействителен токен доступа