openapi: "3.0.1"
info:
  version:  1.0.0 | 01.09.2026
  title: Тренировки пользователя
  description: Информация о тренировках пользователя
servers:
  - url: http://localhost:8080/api/trainings    
tags:
    - name: trainings
paths:
  /getProgress:
   
    post:
      tags: [progress]
      summary: Тренировки пользователя
      description: Метод получает информацию о тренировках пользователя за выбранный период
      requestBody:
        requered: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId: { 
                  type : string,
                  example: "e7883ea2-de24-45c0-ae0e-d65c92a7cff7",
                description: id пользователя
                }
                dateFrom: {
                  type: string,
                  format: date,
                  example: "2026-08-01",
                description: Дата от
                }
                dateTo: {
                  type: string,
                  format: date,
                  example: "2026-08-31",
                  description: Дата по
               }
      responses:
        201:
          description: Тренировки пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                    type: object
                    properties:
                        nameTraining:
                         type: string
                        count:
                         type: integer
              example:
              - name: Strength Training
                count: 25
              - name: Stretching
                count: 30
        204:
          description: No Content
        400:
          description: Bad Request
        401:
          description: Unauthorized
        500:
          description: Internal Service Error
    delete:
      tags: [progress]
      summary: Тренировки пользователя
      description: Метод получает информацию о тренировках пользователя за выбранный период
      requestBody:
        requered: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId: { 
                  type : string,
                  example: "e7883ea2-de24-45c0-ae0e-d65c92a7cff7",
                description: id пользователя
                }
                idTraining: { 
                  type : string,
                  example: "e7883ea2de2445c0ae0ed65c92a70001",
                description: id тренировки
                }
                dateFrom: {
                  type: string,
                  format: date,
                  example: "2026-08-01",
                description: Дата от
                }
                dateTo: {
                  type: string,
                  format: date,
                  example: "2026-08-31",
                  description: Дата по
               }
      responses:
        201:
          description: No Content
        204:
          description: No Content
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
        500:
          description: Internal Service Error

          
  
          
  
